### ISSUE TITLE
The generated identicon is off horizontally and vertically

### ISSUE THREAD

**Issue by LaurentVB** [dmester/jdenticon#6] opened 2015-09-04 12:13 UTC
Hello.
Thank you for this library. I find the generated identicons very elegant.
However, I think that the generated drawing is not properly centered in the canvas.
![screen shot 2015-09-04 at 14 06 10](https://cloud.githubusercontent.com/assets/2806149/9683214/6e62f866-530e-11e5-92d7-de26394f055e.png)
This is of course more visible when the identicon is framed, like on the screenshot above.
By playing with css positioning, I noticed that the drawing is 3px too high and 3 px on the left (for a 140x140 identicon)

Regards,

Laurent

**Comment by dmester** [comment] 2015-09-04 17:57
Hi Laurent,

Thanks for letting me know about this finding. The cause of the icon offset was that the icon size was rounded down to the nearest multiple of 8 to ensure a pixel aligned icon. Unfortunately the offset in size was not reflected in the position of the icon. This will be fixed in the upcoming version 1.3.0.

Best regards,
Daniel

**Closed** 2015-09-04 19:29 UTC
